server:
  port: 9090

feign:
  circuitbreaker:
    enabled:true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

client:
  post:
    baseUrl: https://localhost:8000/...